-- Nimzo database setup: paste this whole file into Supabase -> SQL Editor -> Run.
-- Generated by scripts/gen-setup-sql.ts from supabase/migrations/. Run it once on a fresh project.

-- ===== supabase/migrations/20261003000001_init.sql =====
-- Nimzo initial schema.
-- Every object is prefixed nimzo_ because this Supabase project is shared with other apps.
-- No sign-in: the Next.js server reads and writes with the Supabase secret key,
-- which bypasses RLS. RLS is enabled on every table with no policies, so the
-- public (publishable/anon) key can't read or write anything.

create extension if not exists vector with schema extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Taxonomy (seeded from app/src/lib/taxonomy.ts, see next migration)
-- ---------------------------------------------------------------------------
create table public.nimzo_taxonomy_tags (
  id text primary key,
  dimension text not null check (dimension in ('mistake_type', 'phase', 'root_cause', 'motif', 'level')),
  label text not null,
  description text not null,
  sort_order int not null default 0
);

create table public.nimzo_openings (
  eco text not null,
  name text not null,
  pgn text not null,
  uci text,
  epd text,
  primary key (eco, name, pgn)
);
create index nimzo_openings_epd_idx on public.nimzo_openings (epd);

-- ---------------------------------------------------------------------------
-- Settings (single row)
-- ---------------------------------------------------------------------------
create table public.nimzo_settings (
  id boolean primary key default true check (id),
  chesscom_username text,
  ratings jsonb not null default '{}'::jsonb,          -- snapshot from /stats per time class
  ratings_fetched_at timestamptz,
  thresholds jsonb not null default '{"inaccuracy":0.16,"mistake":0.24,"blunder":0.6,"jev_min_confidence":0.6,"engine_depth":16}'::jsonb,
  session_auto_off_minutes int not null default 60,
  maia_default_elo int,
  backfill_months int not null default 3,
  auto_analyze_recent int not null default 20,
  coach_note text,
  coach_note_updated_at timestamptz,
  updated_at timestamptz not null default now()
);
insert into public.nimzo_settings (id) values (true);

-- chess.com monthly archive cache (ETag / Last-Modified per archive URL)
create table public.nimzo_chesscom_archives (
  url text primary key,
  year int not null,
  month int not null,
  etag text,
  last_modified text,
  last_checked_at timestamptz,
  game_count int not null default 0
);

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------
create table public.nimzo_sessions (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  last_activity_at timestamptz not null default now(),
  ended_reason text check (ended_reason in ('manual', 'auto_off', 'tab_closed', 'stale')),
  rating_start int,
  rating_end int,
  summary jsonb,          -- { headline, takeaway, next_step: { motif, label }, stats: {...} }
  summary_model text,
  summarized_at timestamptz
);
create index nimzo_sessions_started_idx on public.nimzo_sessions (started_at desc);

-- ---------------------------------------------------------------------------
-- Games
-- ---------------------------------------------------------------------------
create type public.nimzo_analysis_status as enum ('imported', 'engine_done', 'facts_done', 'tagged', 'reviewed', 'failed');
create type public.nimzo_game_source as enum ('chesscom', 'practice');

create table public.nimzo_games (
  id uuid primary key default gen_random_uuid(),
  source public.nimzo_game_source not null default 'chesscom',
  chesscom_uuid text unique,
  chesscom_url text unique,
  pgn text not null,
  my_color text not null check (my_color in ('white', 'black')),
  opponent text not null,
  opponent_rating int,
  my_rating int,
  result text not null check (result in ('win', 'loss', 'draw')),
  result_detail text,                 -- chess.com result code: checkmated, timeout, resigned, ...
  time_class text,                    -- bullet | blitz | rapid | daily
  time_control text,
  rated boolean,
  end_time timestamptz not null,
  eco text,
  opening_name text,
  accuracy_ours numeric(5, 2),
  accuracy_chesscom numeric(5, 2),
  blunders int,
  mistakes int,
  inaccuracies int,
  analysis_status public.nimzo_analysis_status not null default 'imported',
  analysis_error text,
  analysis_updated_at timestamptz,
  session_id uuid references public.nimzo_sessions (id) on delete set null,
  practice_opponent jsonb,            -- { engine: 'maia'|'stockfish', level }
  created_at timestamptz not null default now()
);
create index nimzo_games_end_time_idx on public.nimzo_games (end_time desc);
create index nimzo_games_session_idx on public.nimzo_games (session_id);
create index nimzo_games_status_idx on public.nimzo_games (analysis_status);

-- ---------------------------------------------------------------------------
-- Per-ply engine output
-- ply 0 = start position (no move); ply n = position after move n
-- ---------------------------------------------------------------------------
create table public.nimzo_positions (
  game_id uuid not null references public.nimzo_games (id) on delete cascade,
  ply int not null,
  fen text not null,
  san text,
  uci text,
  is_mine boolean not null default false,
  eval_cp int,                -- from white's perspective
  eval_mate int,              -- from white's perspective
  win_pct numeric(6, 3),      -- white's win% (0-100)
  clock_ms int,               -- clock left for the mover after this move
  time_spent_ms int,
  classification text check (classification in ('best', 'good', 'inaccuracy', 'mistake', 'blunder')),
  accuracy numeric(5, 2),
  best_move_uci text,         -- best move in the position BEFORE this ply
  best_move_san text,
  pv_san text[],
  multipv jsonb,
  primary key (game_id, ply)
);

-- ---------------------------------------------------------------------------
-- Mistakes (one per flagged move of mine)
-- ---------------------------------------------------------------------------
create table public.nimzo_mistakes (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.nimzo_games (id) on delete cascade,
  ply int not null,
  source public.nimzo_game_source not null default 'chesscom',
  classification text not null check (classification in ('inaccuracy', 'mistake', 'blunder')),
  facts jsonb not null,
  detectors jsonb not null default '{}'::jsonb,
  tags jsonb not null default '{}'::jsonb,        -- { field: { value, confidence, source } }
  motifs text[] not null default '{}',            -- confident motif ids (for fast stats)
  mistake_type text,
  root_cause text,
  phase text,
  maia jsonb,                                      -- { elo, p_played, p_best, model }
  explanation text,
  explanation_model text,
  related_lesson_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (game_id, ply)
);
create index nimzo_mistakes_tags_gin on public.nimzo_mistakes using gin (tags);
create index nimzo_mistakes_motifs_gin on public.nimzo_mistakes using gin (motifs);
create index nimzo_mistakes_game_idx on public.nimzo_mistakes (game_id);

create table public.nimzo_game_reviews (
  game_id uuid primary key references public.nimzo_games (id) on delete cascade,
  summary jsonb not null,     -- { key_moment, went_well, work_on }
  model text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Knowledge bank
-- ---------------------------------------------------------------------------
create table public.nimzo_knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null,
  filename text not null,
  content_hash text not null,
  page_count int,
  status text not null default 'uploaded' check (status in ('uploaded', 'ingesting', 'done', 'failed')),
  progress jsonb not null default '{}'::jsonb,
  summary jsonb,
  error text,
  uploaded_at timestamptz not null default now(),
  ingested_at timestamptz
);

create table public.nimzo_lessons (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.nimzo_knowledge_documents (id) on delete set null,
  title text not null,
  slug text not null unique,
  category text not null check (category in ('openings', 'tactics', 'middlegame_plans', 'endgames', 'common_blunders', 'beginner_principles')),
  level text,
  page_start int,
  page_end int,
  content_hash text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.nimzo_lesson_chunks (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references public.nimzo_lessons (id) on delete cascade,
  chunk_index int not null,
  heading text,
  content text not null,
  content_hash text not null,
  fens text[] not null default '{}',
  tags jsonb not null default '{}'::jsonb,
  motifs text[] not null default '{}',
  phase text,
  mistake_type text,
  level text,
  eco text,
  page_start int,
  page_end int,
  token_count int,
  embedding vector(1024),   -- Voyage voyage-4 family, 1024 dims (unqualified: works whichever schema holds pgvector)
  unique (lesson_id, chunk_index)
);
create index nimzo_lesson_chunks_motifs_gin on public.nimzo_lesson_chunks using gin (motifs);
create index nimzo_lesson_chunks_hash_idx on public.nimzo_lesson_chunks (content_hash);
create index nimzo_lesson_chunks_embedding_idx on public.nimzo_lesson_chunks
  using hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- Puzzles
-- ---------------------------------------------------------------------------
create table public.nimzo_puzzles (
  id text primary key,                 -- Lichess PuzzleId
  fen text not null,
  moves text[] not null,               -- UCI; first move is the opponent's setup move
  rating int not null,
  rating_deviation int,
  popularity int,
  lichess_themes text[] not null default '{}',
  motifs text[] not null default '{}',
  opening_tags text[] not null default '{}'
);
create index nimzo_puzzles_motifs_gin on public.nimzo_puzzles using gin (motifs);
create index nimzo_puzzles_rating_idx on public.nimzo_puzzles (rating);

create table public.nimzo_puzzle_attempts (
  id uuid primary key default gen_random_uuid(),
  puzzle_id text not null references public.nimzo_puzzles (id) on delete cascade,
  motif text,
  solved boolean not null,
  time_taken_ms int,
  attempted_at timestamptz not null default now()
);
create index nimzo_puzzle_attempts_motif_idx on public.nimzo_puzzle_attempts (motif, attempted_at desc);

-- ---------------------------------------------------------------------------
-- Coach chat
-- ---------------------------------------------------------------------------
create table public.nimzo_chat_threads (
  id uuid primary key default gen_random_uuid(),
  title text,
  game_id uuid references public.nimzo_games (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.nimzo_chat_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.nimzo_chat_threads (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content jsonb not null,        -- Anthropic content blocks (text, tool_use, tool_result)
  engine_context jsonb,          -- Stockfish lines the client attached
  model text,
  created_at timestamptz not null default now()
);
create index nimzo_chat_messages_thread_idx on public.nimzo_chat_messages (thread_id, created_at);

-- ---------------------------------------------------------------------------
-- Error log
-- ---------------------------------------------------------------------------
create table public.nimzo_error_log (
  id bigint generated always as identity primary key,
  at timestamptz not null default now(),
  scope text not null,           -- e.g. 'sync', 'analysis.facts', 'jev', 'claude'
  game_id uuid references public.nimzo_games (id) on delete set null,
  message text not null,
  detail jsonb
);
create index nimzo_error_log_at_idx on public.nimzo_error_log (at desc);

-- ---------------------------------------------------------------------------
-- Pattern stats: motif counts over my last N analyzed games (default 30)
-- ---------------------------------------------------------------------------
create or replace function public.nimzo_pattern_stats(window_games int default 30, include_practice boolean default false)
returns table (motif text, games int, occurrences int)
language sql
stable
set search_path = ''
as $$
  with recent as (
    select g.id
    from public.nimzo_games g
    where g.analysis_status in ('tagged', 'reviewed')
      and (include_practice or g.source = 'chesscom')
    order by g.end_time desc
    limit window_games
  )
  select m_motif as motif,
         count(distinct m.game_id)::int as games,
         count(*)::int as occurrences
  from public.nimzo_mistakes m
  join recent r on r.id = m.game_id
  cross join lateral unnest(m.motifs) as m_motif
  group by m_motif
  order by games desc, occurrences desc;
$$;

-- ---------------------------------------------------------------------------
-- RLS on, no policies: only the server's secret key can access these tables.
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'nimzo_taxonomy_tags', 'nimzo_openings', 'nimzo_settings', 'nimzo_chesscom_archives', 'nimzo_sessions', 'nimzo_games', 'nimzo_positions', 'nimzo_mistakes', 'nimzo_game_reviews', 'nimzo_knowledge_documents', 'nimzo_lessons', 'nimzo_lesson_chunks', 'nimzo_puzzles', 'nimzo_puzzle_attempts', 'nimzo_chat_threads', 'nimzo_chat_messages', 'nimzo_error_log'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Private storage bucket for the knowledge PDF (server uploads with the secret key)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('nimzo-knowledge', 'nimzo-knowledge', false)
on conflict (id) do nothing;

-- ===== supabase/migrations/20261003000002_taxonomy_seed.sql =====
-- GENERATED by scripts/gen-taxonomy-sql.ts from app/src/lib/taxonomy.ts. Do not edit by hand.
delete from public.nimzo_taxonomy_tags;
insert into public.nimzo_taxonomy_tags (id, dimension, label, description, sort_order) values
  ('mistake_type:tactical', 'mistake_type', 'Tactical', 'A concrete tactic was missed or allowed.', 0),
  ('mistake_type:positional', 'mistake_type', 'Positional', 'A long-term concession: structure, piece placement, or plan.', 1),
  ('mistake_type:opening', 'mistake_type', 'Opening', 'Went wrong in the opening: theory, development, or principles.', 2),
  ('mistake_type:endgame_technique', 'mistake_type', 'Endgame technique', 'Mishandled a simplified position.', 3),
  ('mistake_type:time_management', 'mistake_type', 'Time management', 'The clock, not the position, caused the error.', 4),
  ('phase:opening', 'phase', 'Opening', 'Roughly the first 10–12 moves, before development is complete.', 0),
  ('phase:middlegame', 'phase', 'Middlegame', 'Pieces developed, most material still on the board.', 1),
  ('phase:endgame', 'phase', 'Endgame', 'Queens off or little material left.', 2),
  ('root_cause:missed_opponent_threat', 'root_cause', 'Missed the opponent''s threat', 'The opponent''s last move created a threat and the player didn''t notice it.', 0),
  ('root_cause:didnt_see_reply', 'root_cause', 'Didn''t see their reply', 'The player didn''t see the opponent''s strongest answer to this move.', 1),
  ('root_cause:missed_own_tactic', 'root_cause', 'Missed your own tactic', 'A tactic was available for the player and they didn''t see it.', 2),
  ('root_cause:miscalculated', 'root_cause', 'Miscalculated', 'The player went for a sequence but got it wrong partway through.', 3),
  ('root_cause:time_pressure', 'root_cause', 'Time pressure', 'Very little time on the clock forced a rushed move.', 4),
  ('root_cause:rushed_with_time', 'root_cause', 'Rushed with time left', 'The player had time but moved too fast.', 5),
  ('root_cause:overthought', 'root_cause', 'Overthought it', 'Spent a long time and still chose badly.', 6),
  ('root_cause:greed', 'root_cause', 'Greed', 'Went for material and ignored the danger.', 7),
  ('root_cause:fear', 'root_cause', 'Played scared', 'Defended against a threat that wasn''t real, or played too cautiously.', 8),
  ('root_cause:relaxed_when_winning', 'root_cause', 'Relaxed when winning', 'Was ahead and stopped being careful.', 9),
  ('root_cause:tilt', 'root_cause', 'Tilt', 'Followed another recent mistake; frustration or panic.', 10),
  ('root_cause:unfamiliar_position', 'root_cause', 'Unfamiliar position', 'Didn''t know the typical plan or pattern in this kind of position.', 11),
  ('root_cause:principle_ignored', 'root_cause', 'Ignored a basic principle', 'Broke a basic principle (development, king safety, center).', 12),
  ('root_cause:unclear', 'root_cause', 'Unclear', 'The facts don''t point to one cause.', 13),
  ('motif:hung_queen', 'motif', 'Hung the queen', 'You left your queen where it could be taken.', 0),
  ('motif:hung_rook', 'motif', 'Hung a rook', 'You left a rook where it could be taken for free or for less.', 1),
  ('motif:hung_minor', 'motif', 'Hung a knight or bishop', 'You left a knight or bishop unprotected and it could be taken.', 2),
  ('motif:hung_pawn', 'motif', 'Dropped a pawn', 'You let a pawn be taken for nothing.', 3),
  ('motif:hung_moved_piece', 'motif', 'Moved a piece to an unsafe square', 'The piece you just moved can be taken right away.', 4),
  ('motif:unprotected_other_piece', 'motif', 'Left another piece unprotected', 'Your move stopped protecting one of your other pieces.', 5),
  ('motif:hanging_after_capture', 'motif', 'Hung a piece right after a capture', 'In the middle of trading pieces, you left something hanging.', 6),
  ('motif:ignored_threat', 'motif', 'Ignored a threat', 'Your opponent was attacking one of your pieces and you didn''t deal with it.', 7),
  ('motif:allowed_fork', 'motif', 'Walked into a fork', 'You let your opponent attack two of your pieces at once.', 8),
  ('motif:allowed_knight_fork', 'motif', 'Walked into a knight fork', 'You let a knight jump in and attack two of your pieces at once.', 9),
  ('motif:allowed_pin', 'motif', 'Walked into a pin', 'You let your opponent pin one of your pieces so it can''t move safely.', 10),
  ('motif:allowed_skewer', 'motif', 'Walked into a skewer', 'You lined up a valuable piece in front of another one and got skewered.', 11),
  ('motif:allowed_discovered_attack', 'motif', 'Allowed a discovered attack', 'You let your opponent move one piece to reveal an attack from another.', 12),
  ('motif:allowed_mate', 'motif', 'Allowed checkmate', 'After your move, your opponent had a forced checkmate.', 13),
  ('motif:allowed_mate_threat', 'motif', 'Allowed a mating attack', 'Your move let your opponent start a mating attack.', 14),
  ('motif:allowed_trapped_piece', 'motif', 'Let a piece get trapped', 'Your opponent could trap one of your pieces so it had nowhere to go.', 15),
  ('motif:allowed_promotion', 'motif', 'Let a pawn promote', 'You let your opponent''s pawn reach the end and become a queen.', 16),
  ('motif:losing_capture', 'motif', 'Captured into a loss', 'You took something, but lost more than you won when they took back.', 17),
  ('motif:bad_exchange', 'motif', 'Gave up a stronger piece for a weaker one', 'You traded a more valuable piece for a less valuable one.', 18),
  ('motif:moved_pinned_piece_line', 'motif', 'Broke a pin badly', 'You moved a pinned piece and exposed something more valuable behind it.', 19),
  ('motif:stalemated_opponent', 'motif', 'Stalemated a winning game', 'You were winning but left your opponent with no legal moves: a draw.', 20),
  ('motif:back_rank_weakness', 'motif', 'Back-rank weakness', 'Your king was stuck on the back row with no escape square.', 21),
  ('motif:missed_free_piece', 'motif', 'Missed a free piece', 'Your opponent left a piece hanging and you didn''t take it.', 22),
  ('motif:missed_free_pawn', 'motif', 'Missed a free pawn', 'There was a free pawn to take and you didn''t take it.', 23),
  ('motif:missed_mate', 'motif', 'Missed checkmate', 'You had a forced checkmate and didn''t play it.', 24),
  ('motif:missed_mate_in_one', 'motif', 'Missed mate in one', 'You could have checkmated in one move.', 25),
  ('motif:missed_fork', 'motif', 'Missed a fork', 'You could have attacked two pieces at once.', 26),
  ('motif:missed_pin', 'motif', 'Missed a pin', 'You could have pinned one of their pieces.', 27),
  ('motif:missed_skewer', 'motif', 'Missed a skewer', 'You could have attacked a valuable piece and won the one behind it.', 28),
  ('motif:missed_discovered_attack', 'motif', 'Missed a discovered attack', 'You could have moved one piece to reveal an attack from another.', 29),
  ('motif:missed_winning_check', 'motif', 'Missed a winning check', 'A check would have won material or the game.', 30),
  ('motif:missed_trap', 'motif', 'Missed trapping a piece', 'You could have trapped one of their pieces.', 31),
  ('motif:missed_promotion', 'motif', 'Missed promoting', 'You could have pushed a pawn to the end and made a queen.', 32),
  ('motif:missed_punishment', 'motif', 'Didn''t punish their mistake', 'Your opponent had just made a mistake and you didn''t take advantage.', 33),
  ('motif:missed_material_win', 'motif', 'Missed winning material', 'There was a way to win material and you played something else.', 34),
  ('motif:missed_queen_attack', 'motif', 'Missed attacking the queen', 'You could have attacked their queen and gained time.', 35),
  ('motif:found_fork', 'motif', 'Found a fork', 'You attacked two pieces at once.', 36),
  ('motif:found_pin', 'motif', 'Found a pin', 'You pinned one of their pieces.', 37),
  ('motif:found_skewer', 'motif', 'Found a skewer', 'You skewered their pieces.', 38),
  ('motif:found_discovered_attack', 'motif', 'Found a discovered attack', 'You uncovered an attack from another piece.', 39),
  ('motif:found_mate', 'motif', 'Delivered checkmate', 'You checkmated your opponent.', 40),
  ('motif:won_free_piece', 'motif', 'Took a free piece', 'You took a piece your opponent left hanging.', 41),
  ('motif:trapped_piece', 'motif', 'Trapped a piece', 'You trapped one of their pieces.', 42),
  ('motif:punished_mistake', 'motif', 'Punished their mistake', 'Your opponent slipped and you made them pay.', 43),
  ('motif:sound_sacrifice', 'motif', 'Sound sacrifice', 'You gave up material on purpose and it worked.', 44),
  ('motif:promoted', 'motif', 'Promoted a pawn', 'You turned a pawn into a new queen.', 45),
  ('motif:early_queen', 'motif', 'Brought the queen out early', 'You moved your queen out before your other pieces were ready.', 46),
  ('motif:same_piece_twice', 'motif', 'Moved the same piece twice', 'You moved one piece again in the opening instead of developing a new one.', 47),
  ('motif:slow_development', 'motif', 'Slow development', 'Most of your knights and bishops were still at home.', 48),
  ('motif:not_castled', 'motif', 'King still in the middle', 'Your king was still in the middle of the board and not castled.', 49),
  ('motif:lost_castling', 'motif', 'Gave up the right to castle', 'You moved your king or rook and can''t castle anymore.', 50),
  ('motif:f_pawn_weakening', 'motif', 'Weakened the king with the f-pawn', 'You pushed the pawn next to your king early, opening a path to it.', 51),
  ('motif:edge_pawn_moves', 'motif', 'Edge pawn moves in the opening', 'You spent opening moves pushing edge pawns instead of developing.', 52),
  ('motif:knight_on_rim', 'motif', 'Knight on the edge', 'You put a knight on the edge of the board where it does little.', 53),
  ('motif:queen_pawn_grab', 'motif', 'Grabbed a pawn with the queen', 'You went pawn-hunting with your queen in the opening.', 54),
  ('motif:castled_early', 'motif', 'Castled on time', 'You got your king safe early.', 55),
  ('motif:developed_piece', 'motif', 'Developed a piece', 'You brought a new knight or bishop into the game.', 56),
  ('motif:book_move', 'motif', 'Book move', 'A standard opening move.', 57),
  ('motif:ignored_center', 'motif', 'Ignored the center', 'The move did nothing for the center while the opponent took it.', 58),
  ('motif:opening_trap_fell', 'motif', 'Fell for an opening trap', 'The move falls for a known early trap.', 59),
  ('motif:blocked_own_pieces', 'motif', 'Blocked your own pieces', 'The move gets in the way of your own bishop or pawns.', 60),
  ('motif:premature_attack_opening', 'motif', 'Attacked before developing', 'You started an attack before your pieces were out.', 61),
  ('motif:weakened_king_shelter', 'motif', 'Weakened your king''s shelter', 'You moved a pawn that was protecting your king.', 62),
  ('motif:king_under_fire', 'motif', 'King under fire', 'Several enemy pieces were aiming at your king.', 63),
  ('motif:opened_lines_to_king', 'motif', 'Opened lines to your king', 'Your move opened a path for enemy pieces toward your king.', 64),
  ('motif:king_walk', 'motif', 'Took a king walk', 'You moved your king out into the open.', 65),
  ('motif:neglected_king_safety', 'motif', 'Neglected king safety', 'You focused elsewhere while your king was getting exposed.', 66),
  ('motif:created_doubled_pawns', 'motif', 'Doubled your pawns', 'You ended up with two pawns stacked on the same file.', 67),
  ('motif:created_isolated_pawn', 'motif', 'Isolated a pawn', 'You left a pawn with no friendly pawns beside it.', 68),
  ('motif:gave_passed_pawn', 'motif', 'Gave your opponent a passed pawn', 'Your opponent got a pawn nothing can stop from advancing.', 69),
  ('motif:created_passed_pawn', 'motif', 'Created a passed pawn', 'You made a pawn that nothing can stop from advancing.', 70),
  ('motif:weak_squares', 'motif', 'Created weak squares', 'Your pawn move left holes the opponent''s pieces can sit in.', 71),
  ('motif:overextended_pawns', 'motif', 'Pushed pawns too far', 'Your pawns ran too far ahead and became targets.', 72),
  ('motif:traded_when_behind', 'motif', 'Traded while behind', 'You swapped pieces while down material, which usually helps the opponent.', 73),
  ('motif:traded_when_ahead', 'motif', 'Traded while ahead', 'You swapped pieces while up material: good technique.', 74),
  ('motif:gave_up_bishop_pair', 'motif', 'Gave up the bishop pair', 'You traded a bishop for a knight and lost your two-bishop advantage.', 75),
  ('motif:even_trade', 'motif', 'Even trade', 'You traded pieces of equal value.', 76),
  ('motif:queen_trade_when_behind', 'motif', 'Traded queens while behind', 'You traded queens while losing on material.', 77),
  ('motif:time_scramble', 'motif', 'Time scramble', 'You had under 30 seconds left.', 78),
  ('motif:low_time', 'motif', 'Low on time', 'You had under a minute left.', 79),
  ('motif:rushed_critical_move', 'motif', 'Rushed a critical move', 'You moved in a few seconds at a moment that needed thought.', 80),
  ('motif:instant_blunder', 'motif', 'Blundered instantly', 'You played a losing move almost instantly.', 81),
  ('motif:long_think_blunder', 'motif', 'Thought long, still blundered', 'You spent a long time and still made a big mistake.', 82),
  ('motif:long_think', 'motif', 'Long think', 'You took much longer than usual on this move.', 83),
  ('motif:time_trouble_self_inflicted', 'motif', 'Fell behind on the clock', 'You had far less time than your opponent.', 84),
  ('motif:blunder_when_winning', 'motif', 'Threw away a winning position', 'You were winning and this move gave much of it back.', 85),
  ('motif:mistake_when_equal', 'motif', 'Slipped in an equal position', 'The game was even and this move put you behind.', 86),
  ('motif:collapse_when_losing', 'motif', 'Made a bad position worse', 'You were already worse and this move made it much worse.', 87),
  ('motif:tilt_followup', 'motif', 'Mistake right after a mistake', 'This came right after another big mistake of yours.', 88),
  ('motif:recapture_reflex', 'motif', 'Automatic recapture', 'You took back right away when something better was there.', 89),
  ('motif:forced_reply', 'motif', 'Only move', 'This was your only legal move.', 90),
  ('motif:held_advantage', 'motif', 'Kept your advantage', 'You were ahead and kept it with a solid move.', 91),
  ('motif:defended_threat', 'motif', 'Defended a threat', 'Your opponent threatened something and you dealt with it.', 92),
  ('motif:missed_overloaded_defender', 'motif', 'Missed an overloaded defender', 'One of their pieces was guarding two things and you could have exploited it.', 93),
  ('motif:missed_removal_of_defender', 'motif', 'Missed removing the defender', 'You could have captured or chased away the piece that was guarding something.', 94),
  ('motif:missed_deflection', 'motif', 'Missed a deflection', 'You could have lured a defender away from its job.', 95),
  ('motif:missed_zwischenzug', 'motif', 'Missed an in-between move', 'Instead of the obvious reply, a stronger in-between move (often a check) was there.', 96),
  ('motif:missed_counterattack', 'motif', 'Missed a counterattack', 'Instead of defending, you could have hit back with a bigger threat.', 97),
  ('motif:overloaded_own_defender', 'motif', 'Overloaded your own defender', 'One of your pieces had to guard too many things at once.', 98),
  ('motif:removed_own_defender', 'motif', 'Moved away a defender', 'You moved a piece that was protecting something important.', 99),
  ('motif:allowed_deflection', 'motif', 'Allowed a deflection', 'You let your opponent lure your defender away.', 100),
  ('motif:allowed_x_ray', 'motif', 'Allowed an x-ray attack', 'Your opponent''s piece could attack through one of yours to another behind it.', 101),
  ('motif:allowed_perpetual', 'motif', 'Allowed a perpetual check', 'You let your opponent force a draw by checking forever.', 102),
  ('motif:miscounted_exchange', 'motif', 'Miscounted attackers and defenders', 'You started a trade without counting how many pieces attacked and defended the square.', 103),
  ('motif:aimless_move', 'motif', 'Aimless move', 'The move didn''t have a clear purpose.', 104),
  ('motif:passive_retreat', 'motif', 'Passive retreat', 'You pulled a piece back when it was doing a good job.', 105),
  ('motif:premature_attack', 'motif', 'Attacked too early', 'You attacked before your pieces were ready to support it.', 106),
  ('motif:pawn_grab_greed', 'motif', 'Greedy pawn grab', 'You went for a pawn and fell behind in development or safety.', 107),
  ('motif:piece_misplaced', 'motif', 'Misplaced a piece', 'You put a piece on a square where it does little.', 108),
  ('motif:lost_initiative', 'motif', 'Gave up the initiative', 'You were pressing and this move let your opponent take over.', 109),
  ('motif:wrong_plan', 'motif', 'Wrong plan', 'The idea behind the move doesn''t fit the position.', 110),
  ('motif:ignored_opponent_plan', 'motif', 'Ignored the opponent''s plan', 'Your opponent was building something and you didn''t stop it.', 111),
  ('motif:unnecessary_trade', 'motif', 'Unnecessary trade', 'You traded off a good piece for no reason.', 112),
  ('motif:bad_bishop', 'motif', 'Locked in your own bishop', 'Your pawns ended up on the same color as your bishop, blocking it.', 113),
  ('motif:rook_inactive', 'motif', 'Inactive rook', 'Your rook stayed passive instead of taking an open line.', 114),
  ('motif:gave_up_center', 'motif', 'Gave up the center', 'You let the opponent take control of the middle of the board.', 115),
  ('motif:overcomplicated', 'motif', 'Overcomplicated', 'There was a simple safe move and you chose a risky one.', 116),
  ('motif:passive_king_endgame', 'motif', 'Passive king in the endgame', 'In the endgame your king should come forward and fight; it stayed back.', 117),
  ('motif:ignored_passed_pawn', 'motif', 'Ignored a passed pawn', 'A passed pawn needed to be pushed or stopped and you didn''t.', 118),
  ('motif:wrong_pawn_push', 'motif', 'Wrong pawn push', 'You pushed the wrong pawn and it hurt your endgame.', 119),
  ('motif:failed_conversion', 'motif', 'Failed to convert', 'You were winning the endgame and let it slip.', 120),
  ('motif:rook_behind_wrong', 'motif', 'Rook in the wrong place', 'In rook endgames the rook belongs behind passed pawns; it wasn''t.', 121),
  ('motif:missed_simplification', 'motif', 'Didn''t simplify when ahead', 'You were ahead and could have traded down to an easy win.', 122),
  ('motif:opposition_error', 'motif', 'Opposition mistake', 'In a king and pawn endgame you lost the key king face-off.', 123),
  ('motif:didnt_check_threats', 'motif', 'Didn''t check the opponent''s threat', 'You didn''t ask what your opponent''s last move was threatening.', 124),
  ('motif:hope_chess', 'motif', 'Hope chess', 'You played a move hoping your opponent wouldn''t see the reply.', 125),
  ('motif:one_move_thinking', 'motif', 'Only thought one move ahead', 'You looked at your move but not at the opponent''s best answer.', 126),
  ('motif:tunnel_vision', 'motif', 'Tunnel vision', 'You were so focused on one part of the board you missed the rest.', 127),
  ('motif:impulsive', 'motif', 'Impulsive move', 'You played the first move that came to mind.', 128),
  ('motif:didnt_scan_forcing_moves', 'motif', 'Didn''t look for checks and captures', 'There was a strong check or capture and you didn''t look for it.', 129),
  ('motif:assumed_forced_recapture', 'motif', 'Assumed you had to recapture', 'You took back automatically when another move was better.', 130),
  ('motif:relaxed_when_winning', 'motif', 'Relaxed when winning', 'You were ahead and stopped being careful.', 131),
  ('motif:panic_defense', 'motif', 'Panicked', 'Under pressure, you played a desperate move instead of the calm defense.', 132),
  ('motif:trusted_opponent_threat', 'motif', 'Respected a fake threat', 'You defended against something that wasn''t really a threat.', 133),
  ('motif:copied_pattern_wrongly', 'motif', 'Played on autopilot', 'You played a familiar-looking move without checking it fits this position.', 134),
  ('motif:good_prophylaxis', 'motif', 'Good prevention', 'You stopped your opponent''s idea before it happened.', 135),
  ('motif:improved_worst_piece', 'motif', 'Improved your worst piece', 'You brought a poorly placed piece into the game.', 136),
  ('motif:good_defense', 'motif', 'Calm defense', 'You defended accurately under pressure.', 137),
  ('motif:active_king_endgame', 'motif', 'Active king', 'You used your king as a fighting piece in the endgame.', 138),
  ('motif:good_simplification', 'motif', 'Simplified well', 'You traded down into an easy position while ahead.', 139),
  ('motif:seized_open_file', 'motif', 'Took an open file', 'You put a rook on an open line.', 140),
  ('motif:created_threat', 'motif', 'Created a real threat', 'Your move set up a threat your opponent had to answer.', 141),
  ('level:beginner', 'level', 'Beginner', 'Fundamentals.', 0),
  ('level:intermediate', 'level', 'Intermediate', 'Club-level ideas.', 1),
  ('level:advanced', 'level', 'Advanced', 'Deeper strategy and calculation.', 2);

-- ===== supabase/migrations/20261003000003_move_labels.sql =====
-- chess.com's ten move labels (plus "forced"), Miss as a flagged mistake type,
-- and per-game move counts.
alter table public.nimzo_positions drop constraint if exists nimzo_positions_classification_check;
alter table public.nimzo_positions add constraint nimzo_positions_classification_check check (
  classification in ('brilliant', 'great', 'book', 'best', 'excellent', 'good', 'inaccuracy', 'mistake', 'miss', 'blunder', 'forced')
);

alter table public.nimzo_mistakes drop constraint if exists nimzo_mistakes_classification_check;
alter table public.nimzo_mistakes add constraint nimzo_mistakes_classification_check check (
  classification in ('inaccuracy', 'mistake', 'miss', 'blunder')
);

alter table public.nimzo_games add column if not exists misses int;
alter table public.nimzo_games add column if not exists move_count int; -- full moves (White + Black = 1)
create index if not exists nimzo_games_end_time_idx on public.nimzo_games (end_time desc);

-- ===== supabase/migrations/20261003000004_move_features.sql =====
-- Every move of every analyzed game: computed features, tags (rule + Jev),
-- why it was played, and Arthur's one-sentence note. The player profile is
-- built from this table.
create table if not exists public.nimzo_move_features (
  game_id uuid not null references public.nimzo_games (id) on delete cascade,
  ply int not null,
  is_mine boolean not null,
  side text not null check (side in ('white', 'black')),
  move_number int not null,
  san text not null,
  label text,
  phase text,
  features jsonb not null,
  tags text[] not null default '{}',      -- confident tags: rule tags plus Jev tags above the threshold
  jev jsonb,                              -- { tags: {id: probability}, intent, root_cause, model, usage }
  intent text,
  root_cause text,
  note text,                              -- Arthur's one plain sentence about this move
  created_at timestamptz not null default now(),
  primary key (game_id, ply)
);
create index if not exists nimzo_move_features_tags_gin on public.nimzo_move_features using gin (tags);
create index if not exists nimzo_move_features_mine_idx on public.nimzo_move_features (is_mine, label);
alter table public.nimzo_move_features enable row level security;
