-- Nimzo database setup: paste this whole file into Supabase -> SQL Editor -> Run.
-- Generated by scripts/gen-setup-sql.ts from supabase/migrations/. Run it once on a fresh project.

-- ===== supabase/migrations/20261003000001_init.sql =====
-- Nimzo initial schema.
-- No sign-in: the Next.js server reads and writes with the Supabase secret key,
-- which bypasses RLS. RLS is enabled on every table with no policies, so the
-- public (publishable/anon) key can't read or write anything.

create extension if not exists vector with schema extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Taxonomy (seeded from app/src/lib/taxonomy.ts, see next migration)
-- ---------------------------------------------------------------------------
create table public.taxonomy_tags (
  id text primary key,
  dimension text not null check (dimension in ('mistake_type', 'phase', 'root_cause', 'motif', 'level')),
  label text not null,
  description text not null,
  sort_order int not null default 0
);

create table public.openings (
  eco text not null,
  name text not null,
  pgn text not null,
  uci text,
  epd text,
  primary key (eco, name, pgn)
);
create index openings_epd_idx on public.openings (epd);

-- ---------------------------------------------------------------------------
-- Settings (single row)
-- ---------------------------------------------------------------------------
create table public.settings (
  id boolean primary key default true check (id),
  chesscom_username text,
  ratings jsonb not null default '{}'::jsonb,          -- snapshot from /stats per time class
  ratings_fetched_at timestamptz,
  thresholds jsonb not null default '{"inaccuracy":0.1,"mistake":0.2,"blunder":0.3,"jev_min_confidence":0.6,"engine_depth":16}'::jsonb,
  session_auto_off_minutes int not null default 60,
  maia_default_elo int,
  backfill_months int not null default 3,
  auto_analyze_recent int not null default 20,
  coach_note text,
  coach_note_updated_at timestamptz,
  updated_at timestamptz not null default now()
);
insert into public.settings (id) values (true);

-- chess.com monthly archive cache (ETag / Last-Modified per archive URL)
create table public.chesscom_archives (
  url text primary key,
  year int not null,
  month int not null,
  etag text,
  last_modified text,
  last_checked_at timestamptz,
  game_count int not null default 0
);

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------
create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  last_activity_at timestamptz not null default now(),
  ended_reason text check (ended_reason in ('manual', 'auto_off', 'tab_closed', 'stale')),
  rating_start int,
  rating_end int,
  summary jsonb,          -- { headline, takeaway, next_step: { motif, label }, stats: {...} }
  summary_model text,
  summarized_at timestamptz
);
create index sessions_started_idx on public.sessions (started_at desc);

-- ---------------------------------------------------------------------------
-- Games
-- ---------------------------------------------------------------------------
create type public.analysis_status as enum ('imported', 'engine_done', 'facts_done', 'tagged', 'reviewed', 'failed');
create type public.game_source as enum ('chesscom', 'practice');

create table public.games (
  id uuid primary key default gen_random_uuid(),
  source public.game_source not null default 'chesscom',
  chesscom_uuid text unique,
  chesscom_url text unique,
  pgn text not null,
  my_color text not null check (my_color in ('white', 'black')),
  opponent text not null,
  opponent_rating int,
  my_rating int,
  result text not null check (result in ('win', 'loss', 'draw')),
  result_detail text,                 -- chess.com result code: checkmated, timeout, resigned, ...
  time_class text,                    -- bullet | blitz | rapid | daily
  time_control text,
  rated boolean,
  end_time timestamptz not null,
  eco text,
  opening_name text,
  accuracy_ours numeric(5, 2),
  accuracy_chesscom numeric(5, 2),
  blunders int,
  mistakes int,
  inaccuracies int,
  analysis_status public.analysis_status not null default 'imported',
  analysis_error text,
  analysis_updated_at timestamptz,
  session_id uuid references public.sessions (id) on delete set null,
  practice_opponent jsonb,            -- { engine: 'maia'|'stockfish', level }
  created_at timestamptz not null default now()
);
create index games_end_time_idx on public.games (end_time desc);
create index games_session_idx on public.games (session_id);
create index games_status_idx on public.games (analysis_status);

-- ---------------------------------------------------------------------------
-- Per-ply engine output
-- ply 0 = start position (no move); ply n = position after move n
-- ---------------------------------------------------------------------------
create table public.positions (
  game_id uuid not null references public.games (id) on delete cascade,
  ply int not null,
  fen text not null,
  san text,
  uci text,
  is_mine boolean not null default false,
  eval_cp int,                -- from white's perspective
  eval_mate int,              -- from white's perspective
  win_pct numeric(6, 3),      -- white's win% (0-100)
  clock_ms int,               -- clock left for the mover after this move
  time_spent_ms int,
  classification text check (classification in ('best', 'good', 'inaccuracy', 'mistake', 'blunder')),
  accuracy numeric(5, 2),
  best_move_uci text,         -- best move in the position BEFORE this ply
  best_move_san text,
  pv_san text[],
  multipv jsonb,
  primary key (game_id, ply)
);

-- ---------------------------------------------------------------------------
-- Mistakes (one per flagged move of mine)
-- ---------------------------------------------------------------------------
create table public.mistakes (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games (id) on delete cascade,
  ply int not null,
  source public.game_source not null default 'chesscom',
  classification text not null check (classification in ('inaccuracy', 'mistake', 'blunder')),
  facts jsonb not null,
  detectors jsonb not null default '{}'::jsonb,
  tags jsonb not null default '{}'::jsonb,        -- { field: { value, confidence, source } }
  motifs text[] not null default '{}',            -- confident motif ids (for fast stats)
  mistake_type text,
  root_cause text,
  phase text,
  maia jsonb,                                      -- { elo, p_played, p_best, model }
  explanation text,
  explanation_model text,
  related_lesson_ids uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (game_id, ply)
);
create index mistakes_tags_gin on public.mistakes using gin (tags);
create index mistakes_motifs_gin on public.mistakes using gin (motifs);
create index mistakes_game_idx on public.mistakes (game_id);

create table public.game_reviews (
  game_id uuid primary key references public.games (id) on delete cascade,
  summary jsonb not null,     -- { key_moment, went_well, work_on }
  model text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Knowledge bank
-- ---------------------------------------------------------------------------
create table public.knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null,
  filename text not null,
  content_hash text not null,
  page_count int,
  status text not null default 'uploaded' check (status in ('uploaded', 'ingesting', 'done', 'failed')),
  progress jsonb not null default '{}'::jsonb,
  summary jsonb,
  error text,
  uploaded_at timestamptz not null default now(),
  ingested_at timestamptz
);

create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.knowledge_documents (id) on delete set null,
  title text not null,
  slug text not null unique,
  category text not null check (category in ('openings', 'tactics', 'middlegame_plans', 'endgames', 'common_blunders', 'beginner_principles')),
  level text,
  page_start int,
  page_end int,
  content_hash text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lesson_chunks (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references public.lessons (id) on delete cascade,
  chunk_index int not null,
  heading text,
  content text not null,
  content_hash text not null,
  fens text[] not null default '{}',
  tags jsonb not null default '{}'::jsonb,
  motifs text[] not null default '{}',
  phase text,
  mistake_type text,
  level text,
  eco text,
  page_start int,
  page_end int,
  token_count int,
  embedding vector(1024),   -- Voyage voyage-4 family, 1024 dims (unqualified: works whichever schema holds pgvector)
  unique (lesson_id, chunk_index)
);
create index lesson_chunks_motifs_gin on public.lesson_chunks using gin (motifs);
create index lesson_chunks_hash_idx on public.lesson_chunks (content_hash);
create index lesson_chunks_embedding_idx on public.lesson_chunks
  using hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- Puzzles
-- ---------------------------------------------------------------------------
create table public.puzzles (
  id text primary key,                 -- Lichess PuzzleId
  fen text not null,
  moves text[] not null,               -- UCI; first move is the opponent's setup move
  rating int not null,
  rating_deviation int,
  popularity int,
  lichess_themes text[] not null default '{}',
  motifs text[] not null default '{}',
  opening_tags text[] not null default '{}'
);
create index puzzles_motifs_gin on public.puzzles using gin (motifs);
create index puzzles_rating_idx on public.puzzles (rating);

create table public.puzzle_attempts (
  id uuid primary key default gen_random_uuid(),
  puzzle_id text not null references public.puzzles (id) on delete cascade,
  motif text,
  solved boolean not null,
  time_taken_ms int,
  attempted_at timestamptz not null default now()
);
create index puzzle_attempts_motif_idx on public.puzzle_attempts (motif, attempted_at desc);

-- ---------------------------------------------------------------------------
-- Coach chat
-- ---------------------------------------------------------------------------
create table public.chat_threads (
  id uuid primary key default gen_random_uuid(),
  title text,
  game_id uuid references public.games (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.chat_threads (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content jsonb not null,        -- Anthropic content blocks (text, tool_use, tool_result)
  engine_context jsonb,          -- Stockfish lines the client attached
  model text,
  created_at timestamptz not null default now()
);
create index chat_messages_thread_idx on public.chat_messages (thread_id, created_at);

-- ---------------------------------------------------------------------------
-- Error log
-- ---------------------------------------------------------------------------
create table public.error_log (
  id bigint generated always as identity primary key,
  at timestamptz not null default now(),
  scope text not null,           -- e.g. 'sync', 'analysis.facts', 'jev', 'claude'
  game_id uuid references public.games (id) on delete set null,
  message text not null,
  detail jsonb
);
create index error_log_at_idx on public.error_log (at desc);

-- ---------------------------------------------------------------------------
-- Pattern stats: motif counts over my last N analyzed games (default 30)
-- ---------------------------------------------------------------------------
create or replace function public.pattern_stats(window_games int default 30, include_practice boolean default false)
returns table (motif text, games int, occurrences int)
language sql
stable
set search_path = ''
as $$
  with recent as (
    select g.id
    from public.games g
    where g.analysis_status in ('tagged', 'reviewed')
      and (include_practice or g.source = 'chesscom')
    order by g.end_time desc
    limit window_games
  )
  select m_motif as motif,
         count(distinct m.game_id)::int as games,
         count(*)::int as occurrences
  from public.mistakes m
  join recent r on r.id = m.game_id
  cross join lateral unnest(m.motifs) as m_motif
  group by m_motif
  order by games desc, occurrences desc;
$$;

-- ---------------------------------------------------------------------------
-- RLS on, no policies: only the server's secret key can access these tables.
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'taxonomy_tags', 'openings', 'settings', 'chesscom_archives', 'sessions',
    'games', 'positions', 'mistakes', 'game_reviews', 'knowledge_documents', 'lessons',
    'lesson_chunks', 'puzzles', 'puzzle_attempts', 'chat_threads', 'chat_messages', 'error_log'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Private storage bucket for the knowledge PDF (server uploads with the secret key)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('knowledge', 'knowledge', false)
on conflict (id) do nothing;

-- ===== supabase/migrations/20261003000002_taxonomy_seed.sql =====
-- GENERATED by scripts/gen-taxonomy-sql.ts from app/src/lib/taxonomy.ts. Do not edit by hand.
delete from public.taxonomy_tags;
insert into public.taxonomy_tags (id, dimension, label, description, sort_order) values
  ('mistake_type:tactical', 'mistake_type', 'Tactical', 'A concrete tactic was missed or allowed.', 0),
  ('mistake_type:positional', 'mistake_type', 'Positional', 'A long-term concession: structure, piece placement, or plan.', 1),
  ('mistake_type:opening', 'mistake_type', 'Opening', 'Went wrong in the opening: theory, development, or principles.', 2),
  ('mistake_type:endgame_technique', 'mistake_type', 'Endgame technique', 'Mishandled a simplified position.', 3),
  ('mistake_type:time_management', 'mistake_type', 'Time management', 'The clock, not the position, caused the error.', 4),
  ('phase:opening', 'phase', 'Opening', 'Roughly the first 10–12 moves, before development is complete.', 0),
  ('phase:middlegame', 'phase', 'Middlegame', 'Pieces developed, most material still on the board.', 1),
  ('phase:endgame', 'phase', 'Endgame', 'Queens off or little material left.', 2),
  ('root_cause:time_pressure', 'root_cause', 'Time pressure', 'Little time on the clock forced a rushed move.', 0),
  ('root_cause:missed_opponent_threat', 'root_cause', 'Missed opponent''s threat', 'Didn''t ask what the opponent''s last move was threatening.', 1),
  ('root_cause:calculation_error', 'root_cause', 'Calculation error', 'Saw the idea but calculated the line wrong.', 2),
  ('root_cause:tunnel_vision', 'root_cause', 'Tunnel vision', 'Focused on one plan and stopped checking the rest of the board.', 3),
  ('root_cause:relaxed_when_winning', 'root_cause', 'Relaxed when winning', 'Let up after getting a good position.', 4),
  ('root_cause:unfamiliar_position', 'root_cause', 'Unfamiliar position', 'Didn''t know the typical plans or patterns here.', 5),
  ('root_cause:unclear', 'root_cause', 'Unclear', 'The data doesn''t support a confident cause.', 6),
  ('motif:hanging_piece', 'motif', 'Hanging piece', 'Left a piece attacked and undefended.', 0),
  ('motif:hanging_piece_after_capture', 'motif', 'Hanging piece after a capture', 'Left a piece hanging right after a capture or recapture.', 1),
  ('motif:missed_fork', 'motif', 'Missed fork', 'A fork was available and wasn''t played.', 2),
  ('motif:allowed_fork', 'motif', 'Allowed fork', 'Let the opponent fork two or more pieces.', 3),
  ('motif:missed_pin', 'motif', 'Missed pin', 'A pin was available and wasn''t used.', 4),
  ('motif:allowed_pin', 'motif', 'Allowed pin', 'Walked into a pin.', 5),
  ('motif:skewer', 'motif', 'Skewer', 'A skewer was missed or allowed.', 6),
  ('motif:discovered_attack', 'motif', 'Discovered attack', 'A discovered attack was missed or allowed.', 7),
  ('motif:back_rank', 'motif', 'Back-rank weakness', 'The back rank was weak and it cost material or the game.', 8),
  ('motif:missed_mate', 'motif', 'Missed mate', 'A forced mate was available and wasn''t played.', 9),
  ('motif:allowed_mate_threat', 'motif', 'Allowed mate threat', 'Let the opponent create a mating threat.', 10),
  ('motif:overloaded_defender', 'motif', 'Overloaded defender', 'A defender had too many jobs.', 11),
  ('motif:removal_of_defender', 'motif', 'Removal of the defender', 'A key defender was captured or deflected.', 12),
  ('motif:trapped_piece', 'motif', 'Trapped piece', 'A piece ran out of safe squares.', 13),
  ('motif:bad_trade', 'motif', 'Bad trade', 'Traded into a worse position or gave up a key piece.', 14),
  ('motif:king_safety', 'motif', 'King safety', 'Weakened or neglected the king''s shelter.', 15),
  ('motif:pawn_structure', 'motif', 'Pawn structure', 'Created lasting pawn weaknesses.', 16),
  ('motif:piece_activity', 'motif', 'Piece activity', 'Pieces left passive or poorly placed.', 17),
  ('motif:passive_play', 'motif', 'Passive play', 'Missed a chance to act and drifted.', 18),
  ('motif:premature_attack', 'motif', 'Premature attack', 'Attacked before the position was ready.', 19),
  ('motif:opening_principles', 'motif', 'Opening principles', 'Broke basic opening principles: development, center, castling.', 20),
  ('motif:endgame_conversion', 'motif', 'Endgame conversion', 'Failed to convert a winning endgame.', 21),
  ('level:beginner', 'level', 'Beginner', 'Fundamentals.', 0),
  ('level:intermediate', 'level', 'Intermediate', 'Club-level ideas.', 1),
  ('level:advanced', 'level', 'Advanced', 'Deeper strategy and calculation.', 2);
