// Concatenates supabase/migrations/*.sql into supabase/setup.sql, a single file
// to paste into the Supabase SQL Editor on a fresh project.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const dir = new URL("../supabase/migrations/", import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
const parts = files.map((f) => `-- ===== supabase/migrations/${f} =====\n${readFileSync(new URL(f, dir), "utf8")}`);
const out = new URL("../supabase/setup.sql", import.meta.url);
writeFileSync(
  out,
  `-- Nimzo database setup: paste this whole file into Supabase -> SQL Editor -> Run.\n-- Generated by scripts/gen-setup-sql.ts from supabase/migrations/. Run it once on a fresh project.\n\n${parts.join("\n")}`,
);
console.log(`Wrote ${fileURLToPath(out)} from ${files.length} migrations`);
