// Generates the taxonomy seed migration from app/src/lib/taxonomy.ts.
// Run from /app: `npm run gen:taxonomy` (Node 22.6+ runs TypeScript directly).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { taxonomyRows } from "../app/src/lib/taxonomy.ts";

export function taxonomySql(): string {
  const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
  const values = taxonomyRows()
    .map((r) => `  (${q(r.id)}, ${q(r.dimension)}, ${q(r.label)}, ${q(r.description)}, ${r.sort_order})`)
    .join(",\n");
  return `-- GENERATED by scripts/gen-taxonomy-sql.ts from app/src/lib/taxonomy.ts. Do not edit by hand.
delete from public.taxonomy_tags;
insert into public.taxonomy_tags (id, dimension, label, description, sort_order) values
${values};
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = new URL("../supabase/migrations/20261003000002_taxonomy_seed.sql", import.meta.url);
  writeFileSync(out, taxonomySql());
  console.log(`Wrote ${fileURLToPath(out)}`);
}
