import type { PieceRenderObject } from "react-chessboard";

/** Wooden pieces (public/board/wood, generated by scripts/gen-wood.mjs from the cburnett shapes). */
export const woodPieces: PieceRenderObject = Object.fromEntries(
  ["wP", "wN", "wB", "wR", "wQ", "wK", "bP", "bN", "bB", "bR", "bQ", "bK"].map((p) => [
    p,
    // eslint-disable-next-line @next/next/no-img-element
    () => <img src={`/board/wood/${p}.webp`} alt="" draggable={false} style={{ width: "100%", height: "100%", display: "block" }} />,
  ]),
);

export const BOARD_IMAGE = "/board/wood/board.webp";
/** Grain-free averages of the square textures, for notation contrast. */
export const LIGHT_SQ = "#BBA07C";
export const DARK_SQ = "#715239";
